name: check-libraries

on:
  workflow_call:
    inputs:
      COMPONENTS:
        type: string
        required: true
    secrets:
      WRITER_APP_CLIENT_ID:
        required: false
      WRITER_APP_PRIVATE_KEY:
        required: false

permissions:
  contents: read
  id-token: write
  pull-requests: write

defaults:
  run:
    shell: bash

jobs:

  check-library:
    strategy:
      matrix:
        COMPONENT: ${{ fromJSON(inputs.COMPONENTS) }}
    uses: slingshot-pipelines/workflows/.github/workflows/check-library.yml@check-library/v0
    with:
      COMPONENT: ${{ matrix.COMPONENT }}
    secrets: inherit
