name: check-components

on:
  workflow_call:

permissions:
  contents: read
  id-token: write
  pull-requests: write

defaults:
  run:
    shell: bash

jobs:

  lint:
    name: (.components) lint
    runs-on: ubuntu-latest
    steps:
      -
        uses: actions/checkout@v6
      -
        name: Install jsonschema
        uses: sourcemeta/jsonschema@v15.9.0
      -
        name: Validate .components/info.yml
        run: |
          if [[ ! -f "${PROJECT_FILE}" ]]; then
            echo "::error::Missing ${PROJECT_FILE}"
            exit 1
          fi

          echo "Installing project.schema.json..."
            
          PROJECT_SCHEMA_URL="https://raw.githubusercontent.com/slingshot-pipelines/jsonschemas/main/schemas/project/v1/project.schema.json"
          PROJECT_SCHEMA_DIR="${RUNNER_TEMP}/project-schema"
          PROJECT_SCHEMA_FILE="${PROJECT_SCHEMA_DIR}/project.schema.json"
          
          mkdir "${PROJECT_SCHEMA_DIR}"
          jsonschema install "${PROJECT_SCHEMA_URL}" "${PROJECT_SCHEMA_FILE}"

          echo ""
          echo "Validating '${PROJECT_FILE}'..."
          jsonschema validate "${PROJECT_SCHEMA_FILE}" "${PROJECT_FILE}"
      -
        name: Validate components
        run: |
          echo "Installing component.schema.json..."
          
          COMPONENT_SCHEMA_URL="https://raw.githubusercontent.com/slingshot-pipelines/jsonschemas/main/schemas/component/v1/component.schema.json"
          COMPONENT_SCHEMA_DIR="${RUNNER_TEMP}/component-schema"
          COMPONENT_SCHEMA_FILE="${COMPONENT_SCHEMA_DIR}/component.schema.json"
          
          mkdir "${COMPONENT_SCHEMA_DIR}"
          jsonschema install "${COMPONENT_SCHEMA_URL}" "${COMPONENT_SCHEMA_FILE}"
          
          COMPONENT_FILES=$(find .components \
            -name 'info.yml' \
            -type f \
            -mindepth 2 \
            -maxdepth 2 \
            | sort -u)

          while IFS='' read -r COMPONENT_FILE && [[ -n "$COMPONENT_FILE" ]]; do
            echo "Validating $COMPONENT_FILE..."
            jsonschema validate "${COMPONENT_SCHEMA_FILE}" "${COMPONENT_FILE}"
            
            COMPONENT_TYPE=$(cat "$COMPONENT_FILE" | yq '.type')
            echo "::group::Installing JSON schema for a '$COMPONENT_TYPE' component"
            COMPONENT_SUBSCHEMA_URL="https://raw.githubusercontent.com/slingshot-pipelines/jsonschemas/main/schemas/component/v1/${COMPONENT_TYPE}.schema.json"
            COMPONENT_SUBSCHEMA_DIR="${RUNNER_TEMP}/component-subschema-$COMPONENT_TYPE"
            COMPONENT_SUBSCHEMA_FILE="${COMPONENT_SUBSCHEMA_DIR}/${COMPONENT_TYPE}.schema.json"
            if [[ -e "$COMPONENT_SUBSCHEMA_FILE" ]]; then
              echo "Schema already installed"
            else
              mkdir "${COMPONENT_SUBSCHEMA_DIR}"
              jsonschema install "${COMPONENT_SUBSCHEMA_URL}" "${COMPONENT_SUBSCHEMA_FILE}"
            fi
            echo "::endgroup::"
            
            jsonschema validate "${COMPONENT_SUBSCHEMA_FILE}" "${COMPONENT_FILE}"

          done <<< "$COMPONENT_FILES"
