name: check-lambda

on:
  workflow_call:
    inputs:
      COMPONENT:
        type: string
        required: true
      TERRAFORM_VERSION:
        type: string
        required: true
      TERRAGRUNT_VERSION:
        type: string
        required: true
    secrets:
      WRITER_APP_CLIENT_ID:
        required: false
      WRITER_APP_PRIVATE_KEY:
        required: false

permissions:
  contents: read
  id-token: write
  pull-requests: write

defaults:
  run:
    shell: bash

jobs:

  lint-test-build:
    name: (${{ inputs.COMPONENT }}) lint-test-build
    outputs:
      build-cache-key: ${{ steps.pick-build-cache-params.outputs.cache-key }}
      build-cache-path: ${{ steps.pick-build-cache-params.outputs.cache-path }}
    runs-on: ubuntu-latest
    steps:
      -
        name: Fetch app token
        id: fetch-app-token
        uses: slingshot-pipelines/action-optional-app-token@v0
        with:
          CLIENT_ID: ${{ secrets.WRITER_APP_CLIENT_ID }}
          PRIVATE_KEY: ${{ secrets.WRITER_APP_PRIVATE_KEY }}
      -
        uses: actions/checkout@v6
        with:
          token: ${{ steps.fetch-app-token.outputs.token || github.token }}
      -
        name: Component info
        id: component-info
        uses: slingshot-pipelines/action-component-info@v1
        with:
          component: ${{ inputs.COMPONENT }}
      -
        name: Parse relevant component info
        id: parse-component-info
        env:
          COMPONENT: ${{ inputs.COMPONENT }}
          COMPONENT_INFO: ${{ steps.component-info.outputs.info }}
        run: |
          COMPONENT_PATH=$(echo "$COMPONENT_INFO" | jq -rc '.path')
          if [[ -z "$COMPONENT_PATH" ]]; then
            >&2 echo "Error determining component path"
            exit 1
          fi

          SOURCE_SUBPATH=$(echo "$COMPONENT_INFO" | jq -rc '.subpaths.src')
          if [[ -z "$SOURCE_SUBPATH" ]]; then
            >&2 echo "Error determining source path"
            exit 1
          fi

          echo "src-path=$COMPONENT_PATH/$SOURCE_SUBPATH" | tee -a "$GITHUB_OUTPUT"

          BUILD_SUBPATH=$(echo "$COMPONENT_INFO" | jq -rc '.subpaths.build')
          if [[ -z "$BUILD_SUBPATH" ]]; then
            >&2 echo "Error determining build path"
            exit 1
          fi

          echo "build-path=$COMPONENT_PATH/$BUILD_SUBPATH" | tee -a "$GITHUB_OUTPUT"

          INFRA_SUBPATH=$(echo "$COMPONENT_INFO" | jq -rc '.subpaths.infra')
          if [[ -z "$INFRA_SUBPATH" ]]; then
            >&2 echo "Error determining infra path"
            exit 1
          fi

          echo "infra-path=$COMPONENT_PATH/$INFRA_SUBPATH" | tee -a "$GITHUB_OUTPUT"

          SRC_LANG=$(echo "$COMPONENT_INFO" | jq -rc '.language')
          if [[ -z "$COMPONENT_INFO" ]]; then
            >&2 echo "Error determining source language"
            exit 1
          fi

          echo "language=$SRC_LANG" | tee -a "$GITHUB_OUTPUT"
      -
        uses: actions/setup-go@v6
        if: ${{ steps.parse-component-info.outputs.language == 'go' }}
        with:
          go-version-file: ${{ steps.parse-component-info.outputs.src-path }}/go.mod
          cache-dependency-path: ${{ steps.parse-component-info.outputs.src-path }}/go.sum
      -
        name: Lint source
        working-directory: ${{ steps.parse-component-info.outputs.src-path }}
        run: |
          make lint
      -
        name: Detect changes
        id: detect-changes
        shell: bash
        run: |
          # Check for generated changes

          git status -s

          if [ -n "$(git status -s)" ]; then
            echo "detected=true" | tee -a "$GITHUB_OUTPUT"
          else
            echo "detected=false" | tee -a "$GITHUB_OUTPUT"
          fi
      -
        name: Commit changes if detected
        if: ${{ steps.detect-changes.outputs.detected == 'true' }}
        uses: planetscale/ghcommit-action@v0.2.22
        env:
          GITHUB_TOKEN: ${{ steps.fetch-app-token.outputs.token || github.token }}
        with:
          commit_message: "lint ${{ inputs.COMPONENT }} source code"
          repo: ${{ github.repository }}
          branch: ${{ github.head_ref || github.ref_name }}
      -
        name: Fail if changes
        shell: bash
        if: ${{ steps.detect-changes.outputs.detected == 'true' }}
        run: |
          exit 1
      -
        name: Unit tests
        working-directory: ${{ steps.parse-component-info.outputs.src-path }}
        run: |
          make unit-test
      -
        name: Build executable
        working-directory: ${{ steps.parse-component-info.outputs.src-path }}
        run: |
          make build
      -
        name: Pick build cache parameters
        id: pick-build-cache-params
        env:
          CACHE_KEY: ${{ inputs.COMPONENT }}-${{ github.run_id }}-${{ github.run_attempt }}
          CACHE_DIR: ${{ steps.parse-component-info.outputs.build-path }}
        run: |
          echo "cache-key=$CACHE_KEY" | tee -a "$GITHUB_OUTPUT"
          echo "cache-path=$CACHE_DIR" | tee -a "$GITHUB_OUTPUT"
      -
        name: Cache build output
        id: cache-build-output
        uses: actions/cache/save@v5
        with:
          key: ${{ steps.pick-build-cache-params.outputs.cache-key }}
          path: ${{ steps.pick-build-cache-params.outputs.cache-path }}
  
  check-infra:
    needs:
      - lint-test-build
    uses: slingshot-pipelines/workflows/.github/workflows/check-terragrunt-infra.yml@check-terragrunt-infra/v0
    with:
      TERRAFORM_VERSION: ${{ inputs.TERRAFORM_VERSION }}
      TERRAGRUNT_VERSION: ${{ inputs.TERRAGRUNT_VERSION }}
      COMPONENT: ${{ inputs.COMPONENT }}
      ALL: true
      BUILD_CACHE_KEY: ${{ needs.lint-test-build.outputs.build-cache-key }}
      BUILD_CACHE_PATH: ${{ needs.lint-test-build.outputs.build-cache-path }}
    secrets: inherit
