name: check-github-actions

on:
  workflow_call:
    inputs:
      COMPONENTS:
        required: true
        type: string
        description: A JSON array of GitHub actions to check
      GENERATE_DOCS:
        type: boolean
        required: false
        default: true
    secrets:
      WRITER_APP_CLIENT_ID:
        required: false
      WRITER_APP_PRIVATE_KEY:
        required: false

permissions:
  contents: read
  id-token: write
  pull-requests: write

defaults:
  run:
    shell: bash

jobs:

  check-github-action:
    strategy:
      matrix:
        COMPONENT: ${{ fromJSON(inputs.COMPONENTS) }}
    uses: slingshot-pipelines/workflows/.github/workflows/check-github-action.yml@check-github-action/v0
    with:
      COMPONENT: ${{ matrix.COMPONENT }}
      GENERATE_DOCS: ${{ inputs.GENERATE_DOCS }}
