name: check-components

on:
  workflow_call:

permissions:
  contents: read
  id-token: write
  pull-requests: write

defaults:
  run:
    shell: bash

jobs:

  lint:
    name: (.components) lint
    runs-on: ubuntu-latest
    steps:
      -
        uses: actions/checkout@v6
      -
        name: Install jsonschema
        uses: sourcemeta/jsonschema@v15.9.0
      -
        name: Download schemas
        id: download-json-schemas
        run: |
          echo "Installing project.schema.json..."
            
          PROJECT_SCHEMA_URL="https://raw.githubusercontent.com/slingshot-pipelines/jsonschemas/main/schemas/project/v1/project.schema.json"
          PROJECT_SCHEMA_DIR="${RUNNER_TEMP}/project-schema"
          PROJECT_SCHEMA_FILE="${PROJECT_SCHEMA_DIR}/project.schema.json"
          
          mkdir "${PROJECT_SCHEMA_DIR}"
          jsonschema install "${PROJECT_SCHEMA_URL}" "${PROJECT_SCHEMA_FILE}"

          echo "project-schema-file=$PROJECT_SCHEMA_FILE" | tee -a "$GITHUB_OUTPUT"

          echo ""
          echo "Installing component.schema.json..."
          
          COMPONENT_SCHEMA_URL="https://raw.githubusercontent.com/slingshot-pipelines/jsonschemas/main/schemas/component/v1/component.schema.json"
          COMPONENT_SCHEMA_DIR="${RUNNER_TEMP}/component-schema"
          COMPONENT_SCHEMA_FILE="${COMPONENT_SCHEMA_DIR}/component.schema.json"
          
          mkdir "${COMPONENT_SCHEMA_DIR}"
          jsonschema install "${COMPONENT_SCHEMA_URL}" "${COMPONENT_SCHEMA_FILE}"
          
          echo "component-schema-file=$COMPONENT_SCHEMA_FILE" | tee -a "$GITHUB_OUTPUT"
      -
        name: Validate components
        env:
          PROJECT_SCHEMA_FILE: ${{ steps.download-json-schemas.outputs.project-schema-file }}
          COMPONENT_SCHEMA_FILE: ${{ steps.download-json-schemas.outputs.component-schema-file }}
        run: |
          PROJECT_FILE=".components/info.yml"

          if [[ -f "${PROJECT_FILE}" ]]; then
            jsonschema validate "${PROJECT_SCHEMA_FILE}" "${PROJECT_FILE}" --http
          else
            echo "::error::Missing ${PROJECT_FILE}"
            exit 1
          fi

          COMPONENT_FILES=$(find .components \
            -name 'info.yml' \
            -type f \
            -mindepth 2 \
            -maxdepth 2 \
            | sort -u)

          FAILED=false
          while IFS='' read -r COMPONENT_FILE && [[ -n "$COMPONENT_FILE" ]]; do
            echo "::group::Validating $COMPONENT_FILE"
            jsonschema validate "${COMPONENT_SCHEMA_FILE}" "${COMPONENT_FILE}" --http || FAILED=true
            echo "::endgroup::"
          done <<< "$COMPONENT_FILES"

          if [[ "$FAILED" == "true" ]]; then
            exit 1
          fi
