name: check-terraform-modules

on:
  workflow_call:
    inputs:
      COMPONENT:
        type: string
        required: true
      TERRAFORM_VERSION:
        type: string
        required: true
      TERRAGRUNT_VERSION:
        type: string
        required: true
    secrets:
      WRITER_APP_CLIENT_ID:
        required: false
      WRITER_APP_PRIVATE_KEY:
        required: false

permissions:
  contents: read
  id-token: write

defaults:
  run:
    shell: bash

jobs:

  lint-terraform-modules:
    runs-on: ubuntu-latest
    steps:
      -
        uses: actions/checkout@v6
      -
        name: Components info
        id: components-info
        uses: slingshot-pipelines/action-components-info@v1
      -
        name: Pick modules dir
        id: pick-modules-dir
        env:
          MODULES_DIR: ${{ fromJSON(steps.components-info.outputs.info)[inputs.COMPONENT].path }}
        run: |
          if [[ -z "$MODULES_DIR" ]]; then
            >&2 echo "Error determining modules directory"
            exit 1
          fi

          echo "modules-dir=$MODULES_DIR" | tee -a "$GITHUB_OUTPUT"
      -
        name: Install Terraform & Terragrunt
        uses: slingshot-pipelines/action-terragrunt/install@v0
        with:
          TERRAFORM_VERSION: ${{ inputs.TERRAFORM_VERSION }}
          TERRAGRUNT_VERSION: ${{ inputs.TERRAGRUNT_VERSION }}
      -
        name: Lint Terraform modules
        uses: slingshot-pipelines/action-terraform/lint@v0
        with:
          MODULES_DIR: ${{ steps.pick-modules-dir.outputs.modules-dir }}
          APP_CLIENT_ID: ${{ secrets.WRITER_APP_CLIENT_ID }}
          APP_PRIVATE_KEY: ${{ secrets.WRITER_APP_PRIVATE_KEY }}
