name: check-library

on:
  workflow_call:
    inputs:
      COMPONENT:
        type: string
        required: true
    secrets:
      WRITER_APP_CLIENT_ID:
        required: false
      WRITER_APP_PRIVATE_KEY:
        required: false

permissions:
  contents: read
  id-token: write
  pull-requests: write

defaults:
  run:
    shell: bash

jobs:

  lint-and-test:
    name: (${{ inputs.COMPONENT }}) lint-and-test
    runs-on: ubuntu-latest
    steps:
      -
        name: Fetch app token
        id: fetch-app-token
        uses: slingshot-pipelines/action-optional-app-token@v0
        with:
          CLIENT_ID: ${{ secrets.WRITER_APP_CLIENT_ID }}
          PRIVATE_KEY: ${{ secrets.WRITER_APP_PRIVATE_KEY }}
      -
        uses: actions/checkout@v6
        with:
          token: ${{ steps.fetch-app-token.outputs.token || github.token }}
      -
        name: Lookup component info
        id: lookup-component-info
        uses: slingshot-pipelines/action-component-info@v1
        with:
          component: ${{ inputs.COMPONENT }}
      -
        name: Extract info for this component as outputs
        id: extract-component-info
        env:
          COMPONENT_INFO: ${{ steps.lookup-component-info.outputs.info }}
        run: |
          COMPONENT_PATH=$(echo "$COMPONENT_INFO" | jq -rc '.path')
          if [[ -z "$COMPONENT_PATH" ]]; then
            >&2 echo "Error determining component directory"
            exit 1
          fi

          echo "path=$COMPONENT_PATH" | tee -a "$GITHUB_OUTPUT"

          COMPONENT_SOURCE_LANGUAGE=$(echo "$COMPONENT_INFO" | jq -rc '.source-language')
          if [[ -z "$COMPONENT_SOURCE_LANGUAGE" ]]; then
            >&2 echo "Error determining source language"
            exit 1
          fi

          echo "source-language=$COMPONENT_SOURCE_LANGUAGE" | tee -a "$GITHUB_OUTPUT"
      -
        uses: actions/setup-go@v6
        if: ${{ steps.extract-component-info.outputs.source-language == 'go' }}
        with:
          go-version-file: ${{ steps.extract-component-info.outputs.path }}/go.mod
          cache-dependency-path: ${{ steps.extract-component-info.outputs.path }}/go.mod
      -
        name: Lint source
        working-directory: ${{ steps.extract-component-info.outputs.path }}
        run: |
          make lint
      -
        name: Detect changes
        id: detect-changes
        shell: bash
        run: |
          # Check for generated changes

          git status -s

          if [ -n "$(git status -s)" ]; then
            echo "detected=true" | tee -a "$GITHUB_OUTPUT"
          else
            echo "detected=false" | tee -a "$GITHUB_OUTPUT"
          fi
      -
        name: Commit changes if detected
        if: ${{ steps.detect-changes.outputs.detected == 'true' }}
        uses: planetscale/ghcommit-action@v0.2.20
        env:
          GITHUB_TOKEN: ${{ steps.fetch-app-token.outputs.token || github.token }}
        with:
          commit_message: "lint ${{ inputs.COMPONENT }} source code"
          repo: ${{ github.repository }}
          branch: ${{ github.head_ref || github.ref_name }}
      -
        name: Fail if changes
        shell: bash
        if: ${{ steps.detect-changes.outputs.detected == 'true' }}
        run: |
          exit 1
      -
        name: Unit tests
        working-directory: ${{ steps.extract-component-info.outputs.path }}
        run: |
          make unit-test
