name: deploy-terragrunt-infra

on:
  workflow_call:
    inputs:
      COMPONENT:
        required: true
        type: string
      ENVIRONMENT:
        required: true
        type: string
      TAG:
        required: true
        type: string
      TERRAFORM_VERSION:
        type: string
        required: true
      TERRAGRUNT_VERSION:
        type: string
        required: true

permissions:
  contents: read
  pull-requests: read
  id-token: write

defaults:
  run:
    shell: bash

jobs:

  parse-component-info:
    name: (${{ inputs.COMPONENT }}) parse-component-info
    runs-on: ubuntu-latest
    outputs:
      STACKS_DIR: ${{ steps.parse-stacks-dir.outputs.stacks-dir }}
    steps:
      -
        uses: actions/checkout@v6
      -
        name: Component info
        id: fetch-component-info
        uses: slingshot-pipelines/action-component-info@v1
        with:
          component: ${{ inputs.COMPONENT }}
      -
        name: Parse stacks directory
        id: parse-stacks-dir
        env:
          COMPONENT_INFO: ${{ steps.fetch-component-info.outputs.info }}
        run: |
          COMPONENT_PATH=$(echo "$COMPONENT_INFO" | jq -rc '.path')
          if [[ -z "$COMPONENT_PATH" ]]; then
            >&2 echo "Error determining component path"
            exit 1
          fi

          echo "stacks-dir=$COMPONENT_PATH/stacks" | tee -a "$GITHUB_OUTPUT"

  apply:
    needs: [parse-component-info]
    name: (${{ inputs.COMPONENT }}) terragrunt-apply
    uses: slingshot-pipelines/workflows/.github/workflows/terragrunt-apply.yml@terragrunt-apply/v1
    with:
      COMPONENT: ${{ inputs.COMPONENT }}
      STACK: ${{ inputs.ENVIRONMENT }}
      TAG: ${{ inputs.TAG }}
      TERRAGRUNT_VERSION: ${{ inputs.TERRAGRUNT_VERSION }}
      TERRAFORM_VERSION: ${{ inputs.TERRAFORM_VERSION }}
      STACKS_DIR: ${{ needs.parse-component-info.outputs.STACKS_DIR }}
