name: deploy-lambda

on:
  workflow_call:
    inputs:
      COMPONENT:
        type: string
        required: true
      TAG:
        type: string
        required: true
      ENVIRONMENT:
        type: string
        required: true
      TERRAFORM_VERSION:
        type: string
        required: true
      TERRAGRUNT_VERSION:
        type: string
        required: true
    secrets:
      WRITER_APP_CLIENT_ID:
        required: false
      WRITER_APP_PRIVATE_KEY:
        required: false

permissions:
  contents: read
  id-token: write
  pull-requests: write

defaults:
  run:
    shell: bash

jobs:

  build:
    name: (${{ inputs.COMPONENT }}) build
    outputs:
      infra-path: ${{ steps.parse-component-info.outputs.infra-path }}
      build-path: ${{ steps.parse-component-info.outputs.build-path }}
      cache-key: ${{ steps.pick-cache-key.outputs.cache-key }}
    runs-on: ubuntu-latest
    steps:
      -
        name: Fetch app token
        id: fetch-app-token
        uses: slingshot-pipelines/action-optional-app-token@v0
        with:
          CLIENT_ID: ${{ secrets.WRITER_APP_CLIENT_ID }}
          PRIVATE_KEY: ${{ secrets.WRITER_APP_PRIVATE_KEY }}
      -
        uses: actions/checkout@v6
        with:
          token: ${{ steps.fetch-app-token.outputs.token || github.token }}
      -
        name: Component info
        id: component-info
        uses: slingshot-pipelines/action-component-info@v1
        with:
          component: ${{ inputs.COMPONENT }}
      -
        name: Parse relevant component info
        id: parse-component-info
        env:
          COMPONENT: ${{ inputs.COMPONENT }}
          COMPONENT_INFO: ${{ steps.component-info.outputs.info }}
        run: |
          COMPONENT_PATH=$(echo "$COMPONENT_INFO" | jq -rc '.path')
          if [[ -z "$COMPONENT_PATH" ]]; then
            >&2 echo "Error determining component path"
            exit 1
          fi

          SOURCE_SUBPATH=$(echo "$COMPONENT_INFO" | jq -rc '.subpaths.src')
          if [[ -z "$SOURCE_SUBPATH" ]]; then
            >&2 echo "Error determining source path"
            exit 1
          fi

          echo "src-path=$COMPONENT_PATH/$SOURCE_SUBPATH" | tee -a "$GITHUB_OUTPUT"

          BUILD_SUBPATH=$(echo "$COMPONENT_INFO" | jq -rc '.subpaths.build')
          if [[ -z "$BUILD_SUBPATH" ]]; then
            >&2 echo "Error determining build path"
            exit 1
          fi

          echo "build-path=$COMPONENT_PATH/$BUILD_SUBPATH" | tee -a "$GITHUB_OUTPUT"

          INFRA_SUBPATH=$(echo "$COMPONENT_INFO" | jq -rc '.subpaths.infra')
          if [[ -z "$INFRA_SUBPATH" ]]; then
            >&2 echo "Error determining infra path"
            exit 1
          fi

          echo "infra-path=$COMPONENT_PATH/$INFRA_SUBPATH" | tee -a "$GITHUB_OUTPUT"

          SOURCE_LANGUAGE=$(echo "$COMPONENT_INFO" | jq -rc '.source-language')
          if [[ -z "$COMPONENT_INFO" ]]; then
            >&2 echo "Error determining source language"
            exit 1
          fi

          echo "source-language=$SOURCE_LANGUAGE" | tee -a "$GITHUB_OUTPUT"
      -
        uses: actions/setup-go@v6
        if: ${{ steps.component-info.outputs.language == 'go' }}
        with:
          go-version-file: ${{ steps.parse-component-info.outputs.src-path }}/go.mod
          cache-dependency-path: ${{ steps.parse-component-info.outputs.src-path }}/go.sum
      -
        name: Build executable
        working-directory: ${{ steps.parse-component-info.outputs.src-path }}
        run: |
          make build
      -
        name: Pick cache key
        id: pick-cache-key
        env:
          CACHE_KEY: ${{ inputs.COMPONENT }}-${{ github.run_id }}-${{ github.run_attempt }}
        run: |
          echo "cache-key=$CACHE_KEY" | tee -a "$GITHUB_OUTPUT"
      -
        name: Cache build output
        id: cache-build-output
        uses: actions/cache/save@v5
        with:
          key: ${{ steps.pick-cache-key.outputs.cache-key }}
          path: ${{ steps.parse-component-info.outputs.build-path }}

  apply:
    needs: [build]
    name: (${{ inputs.COMPONENT }}) terragrunt-apply
    uses: slingshot-pipelines/workflows/.github/workflows/terragrunt-apply.yml@terragrunt-apply/v1
    with:
      COMPONENT: ${{ inputs.COMPONENT }}
      STACK: ${{ inputs.ENVIRONMENT }}
      TAG: ${{ inputs.TAG }}
      TERRAGRUNT_VERSION: ${{ inputs.TERRAGRUNT_VERSION }}
      TERRAFORM_VERSION: ${{ inputs.TERRAFORM_VERSION }}
      STACKS_DIR: ${{ needs.build.outputs.infra-path }}/stacks
      BUILD_CACHE_KEY: ${{ needs.build.outputs.cache-key }}
      BUILD_CACHE_PATH: ${{ needs.build.outputs.build-path }}
