name: deploy

on:
  push:
    branches:
      - main

permissions:
  contents: write
  pull-requests: write
  id-token: write

defaults:
  run:
    shell: bash

concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: false

jobs:

  deploy:
    uses: rx-refill-reminders/pipeline/.github/workflows/deploy.yml@deploy/v0
    secrets: inherit
